[versions]
kotlinx-datetime = "0.5.0"
kotlin="2.0.20-RC"
#compose = "1.6.11"
compose = "1.7.0-alpha02"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
